version: '3.8'

services:
  blockchain:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CORS_ORIGIN=http://localhost:3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - blockchain
